# Generated by Django 4.2.8 on 2023-12-24 07:10

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_article_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_content',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
